config/routes.rb
Rails.application.routes.draw do
  if Rails.configuration.x.invitations.enabled
    devise_for :users, controllers: { invitations: 'users/invitations' }
  else
    devise_for :users, skip: :invitations
  end
  get 'directory', to: 'users#index', as: :user_directory
  
  resources :topics, except: %i[edit delete], constraints: { id: /\d+/ } do
    post 'star', to: 'topics#star', as: :star
    post 'unstar', to: 'topics#unstar', as: :unstar
    post 'pin', to: 'topics#pin', as: :pin
    post 'unpin', to: 'topics#unpin', as: :unpin
  end
  get 'topics/mentions', to: 'topics#mentions', as: :my_mentions
  get 'topics/starred', to: 'topics#starred', as: :my_starred
  post 'topics/mark_as_read', to: 'topics#mark_as_read', as: :mark_as_read

  resources :profile, only: %i[show edit update], param: :username
  get 'profile', to: 'profile#mine', as: :my_profile

  root 'topics#index'
end

app/models/topic.rb
class Topic < ApplicationRecord
    has_many :posts, -> { order(created_at: :asc) }
    has_many :topic_views
    has_many :topic_follows

    belongs_to :author, class_name: 'User', inverse_of: :created_topics

    accepts_nested_attributes_for :posts

    validates_presence_of :title, :author

    scope :list_view, -> { includes(:author, posts: [:author]) }

    scope :by_most_recent_post, -> {
      subquery = Post.select(:id)
                     .where("posts.topic_id = topics.id")
                     .order(created_at: :desc).limit(1)
    
      joins(<<-SQL).order('posts.created_at DESC')
        LEFT JOIN posts
          ON posts.topic_id = topics.id
          AND posts.id = (#{subquery.to_sql})
      SQL
    }

    def starred_for?(user)
      topic_follows.where(user: user).any?
    end
end

app/models/topic_view.rb
class TopicView < ApplicationRecord
    belongs_to :user
    belongs_to :topic
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
    after_action :log_topic_view, only: %i[show create update]

    TOPICS_PER_PAGE = 100

    def index
        @total_pages = (Topic.count / TOPICS_PER_PAGE).ceil
        @page_number = params.fetch(:page, 0).to_i

        @topics = Topic.list_view.by_most_recent_post.offset(@page_number * TOPICS_PER_PAGE).limit(TOPICS_PER_PAGE)
        raise ActionController::RoutingError, 'Not Found' if @page_number > 0 && @topics.count.zero?

        setup_for_topics!(@topics)
    end

    def new
        @topic = Topic.new
        @topic.posts.build
    end

    def create
        @topic = Topic.new(topic_params)
        @topic.created_at = Time.now
        @topic.author = current_user
        @topic.posts.first.author = current_user

        if @topic.save
            UserMention.associate_mentions_in_post!(@topic.posts.first)
            redirect_to topic_path(@topic)
        else
            render :new
        end
    end

    def show
        @topic = Topic.find(params[:id])
        @new_post = @topic.posts.build
    end

    def update
        @topic = Topic.find(params[:id])
        @new_post = @topic.posts.build(post_params)
        @new_post.author = current_user

        if @new_post.save
            UserMention.associate_mentions_in_post!(@new_post)
            redirect_to topic_path(@topic)
        else
            render :show
        end
    end

    def star
        @topic = Topic.find(params[:topic_id])
        TopicFollow.create(topic: @topic, user: current_user)

        redirect_to topic_path(@topic)
    end

    def unstar
        @topic = Topic.find(params[:topic_id])
        topic_follows = TopicFollow.where(topic: @topic, user: current_user)
        topic_follows.delete_all

        redirect_to topic_path(@topic)
    end

    def pin
        @topic = Topic.find(params[:topic_id])
        @topic.update(pinned: true)

        redirect_to topic_path(@topic)
    end

    def unpin
        @topic = Topic.find(params[:topic_id])
        @topic.update(pinned: false)

        redirect_to topic_path(@topic)
    end

    def mentions
        mentioned_posts = Post.includes(:user_mentions).where(user_mentions: { user_id: current_user.id })
        @topics = Topic.where(posts: mentioned_posts).list_view.by_most_recent_post
        setup_for_topics!(@topics)
    end

    def starred
        # TODO: This line is breaking when adding the query optimization. Why??
        @topics = Topic.includes(:topic_follows).where(topic_follows: { user: current_user }).by_most_recent_post
        setup_for_topics!(@topics)
    end

    def mark_as_read
        topic_view_attributes = Topic.pluck(:id).map{|topic_id| { topic_id: topic_id, user_id: current_user.id } }
        most_recent_topic_view_ids = TopicView.insert_all!(topic_view_attributes)

        redirect_to topics_path
    end

    private

    def topic_params
        params.require(:topic).permit(:title, :pinned, posts_attributes: [:body])
    end
    
    def post_params
        params.require(:post).permit(:body)
    end

    def log_topic_view
        TopicView.create(user: current_user, topic: @topic)
    end

    def setup_for_topics!(topics)
        @topic_follows = TopicFollow.where(user: current_user).where(topic: topics).order('created_at DESC').group_by{|tv| tv.topic_id }
        @topic_views = TopicView.where(user: current_user).where(topic: topics).order('created_at DESC').group_by{|tv| tv.topic_id }
        @mentions = UserMention.where(user: current_user).includes(:post).where(post: { topic: topics }).order('user_mentions.created_at DESC').group_by{|um| um.post.topic_id }
    end
end

app/helpers/topic_helper.rb
module TopicHelper
    def unread_posts?(topic, views_for_topic)
        return true if views_for_topic.nil? || views_for_topic.none?
        topic.posts.last.created_at > views_for_topic.first.created_at
    end

    def unread_mentions?(mentions_for_topic, views_for_topic)
        return unless mentions_for_topic.present?
        return true unless views_for_topic.present?

        mentions_for_topic.first.created_at > views_for_topic.first.created_at
    end

    def format_body(post_body)
        return unless post_body

        post_body.gsub(UserMention.format_username_regex) {|mention| "<span class='font-bold'>#{mention}</span>" }.html_safe
    end
    
    def page_counter(total_amount, page, items_per_page)
        start_count = (page * items_per_page) + 1
        end_count = (page + 1) * items_per_page

        "#{start_count}-#{[total_amount,end_count].min} of #{total_amount}"
    end
end

app/views/topics/_table.html.erb
<table class="w-full my-3" id="topics-table">
    <thead>
        <tr class="py-1 bg-primary-300 border-b-2 border-secondary-100 text-left">
            <th class="pl-3 w-1">📜<span class="sr-only">notices</span></th>
            <th class="px-3 w-10/12 md:w-7/12 break-all">title</th>
            <th class="px-3 hidden md:table-cell w-1/12">author</th>
            <th class="px-3 hidden md:table-cell w-1/12">#</th>
            <th class="px-3 w-2/12 md:w-1/12">latest <span class="sr-only">poster</span></th>
            <th class="px-3 hidden md:table-cell w-2/12"><span class="sr-only">latest post</span></th>
        </tr>
    </thead>
    <tbody>
        <% topics.each_with_index do |topic, index| %>
            <% views_for_topic = topic_views[topic.id] %>
            <% unread_posts = unread_posts?(topic, views_for_topic) %>
            
            <tr class="py-1 border-b-2 border-secondary-100 <%= SiteTheme.pick_color(index) %> <%= 'font-bold' if unread_posts %>">
                <td class="pl-3 w-1">
                    <% if unread_mentions?(mentions[topic.id], views_for_topic) %>
                        👀
                        <span class="sr-only">mentioned</span>
                    <% end %>
                    <% if topic_follows[topic.id] %>
                        🌟
                        <span class="sr-only">starred</span>
                    <% end %>
                </td>
                <td class="px-3 w-10/12 md:w-6/12 break-all"><%= link_to topic.title, topic_path(topic) %> <span class="sr-only"><%= '(unread)' if unread_posts %></span></td>
                <td class="px-3 hidden md:table-cell w-1/12"><%= link_to topic.author.username, profile_path(topic.author) %></td>
                <td class="px-3 hidden md:table-cell w-1/12"><%= topic.posts.length %></td>
                <td class="px-3 w-2/12 md:w-1/12"><%= link_to topic.posts.last.author.username, profile_path(topic.posts.last.author) %></td>
                <td class="px-3 hidden md:table-cell w-2/12"><%= time_ago_in_words(topic.posts.last.created_at) %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/topics/index.html.erb
<% title("Topics") %>
<% disable_cache %>

<div class="flex justify-between">
    <%= link_to root_path do %>
        <h1 class="text-lg mb-1 px-1 inline-block bg-secondary-300 link--dark">topics</h1>
    <% end %>
    <%= link_to "new topic", new_topic_path, class: "btn inline-block" %>
</div>

<details class="w-full my-3">
    <summary class="py-1 px-1 bg-secondary-200">forum-wide pinned posts</summary>
    <table class="w-full" id="pinned">
        <thead>
            <tr class="bg-secondary-300 border-b-2 border-secondary-100 text-left">
                <th class="px-3 w-10/12 md:w-7/12 break-all">title</th>
                <th class="px-3 hidden md:table-cell w-1/12">author</th>
                <th class="px-3 hidden md:table-cell w-1/12">#</th>
                <th class="px-3 w-2/12 md:w-1/12">latest <span class="sr-only">poster</span></th>
                <th class="px-3 hidden md:table-cell w-2/12"><span class="sr-only">latest post</span></th>
            </tr>
        </thead>
        <tbody>
            <% @topics.where(pinned: true).each do |topic| %>
                <% views_for_topic = @topic_views[topic.id] %>
                <% unread_posts = unread_posts?(topic, views_for_topic) %>
                
                <tr class="py-1 border-b-2 border-secondary-200 bg-secondary-100 <%= 'font-bold' if unread_posts %>">
                    <td class="px-3 w-10/12 md:w-6/12 break-all"><%= link_to topic.title, topic_path(topic) %> <span class="sr-only"><%= '(unread)' if unread_posts %></span></td>
                    <td class="px-3 hidden md:table-cell w-1/12"><%= link_to topic.author.username, profile_path(topic.author) %></td>
                    <td class="px-3 hidden md:table-cell w-1/12"><%= topic.posts.length %></td>
                    <td class="px-3 w-2/12 md:w-1/12"><%= link_to topic.posts.last.author.username, profile_path(topic.posts.last.author) %></td>
                    <td class="px-3 hidden md:table-cell w-2/12"><%= time_ago_in_words(topic.posts.last.created_at) %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
</details>

<div class="flex justify-between" id="table-frontmatter">
    <div class="inline-block align-bottom">
        <span class="text-sm text-primary-100 mr-1">
            <%= page_counter(Topic.count, @page_number, TopicsController::TOPICS_PER_PAGE) %> 
        </span>
        <%= render 'shared/pagination_controls', link_classes: %w[link text-primary-200] %>
    </div>
    <%= button_to "mark all as read", mark_as_read_path, form_class: "inline-block", class: "btn-sm bg-primary-200" %>
</div>

<%= render 'table', topics: @topics, topic_follows: @topic_follows, topic_views: @topic_views, mentions: @mentions %>

<footer>
    <%= render 'shared/pagination_controls', link_classes: %w[my-3 link] %>
</footer>

app/views/topics/mentions.html.erb
<% title("Mentions") %>

<div class="flex justify-between">
    <h1 class="text-lg mb-1 px-1 inline-block bg-secondary-300">topics you've been mentioned in</h1>
    <%= link_to "new topic", new_topic_path, class: "btn inline-block" %>
</div>

<%= render 'table', topics: @topics, topic_follows: @topic_follows, topic_views: @topic_views, mentions: @mentions %>

<%= link_to "back to topics", topics_path, class: "link mb-3" %>

app/views/topics/new.html.erb
<% title("New topic") %>

<h1 class="text-lg mb-1 px-1 inline-block bg-secondary-300">new topic</h1>
<%= form_with model: @topic, class: "py-2" do |f| %>
    <%= render 'shared/errors', errors: @topic.errors if @topic.errors.any? %>

    <%= f.label :title, "title", class: "block font-semibold text-primary-100" %>
    <%= f.text_field :title, class: "border-none w-full md:w-6/12 py-1 px-1 mb-3 bg-primary-100" %>
    
    <%= f.fields_for :posts do |ff| %>
        <%= ff.label :body, "body", class: "block font-semibold text-primary-100" %>
        <%= ff.text_area :body, class: "form-textarea border-none w-full h-36 md:w-6/12 py-1 px-1 mb-3 bg-primary-100" %>
    <% end %>

    <%= f.submit "post", class: "block btn" %>
<% end %>

app/views/topics/show.html.erb
<% title(@topic.title) %>

<div class="pb-2">
    <%= link_to '▼ jump to bottom', '#last-post', class: "link link--light" %>
    <div class="bg-primary-500">
        <div class="bg-primary-400 px-2 py-1 flex justify-between">
            <div>
                <h1 class="text-lg break-all"><%= @topic.title %></h1>
                <h2 class="text-xs"><%= link_to @topic.author.username, profile_path(@topic.author) %> | <%= time_ago_in_words(@topic.created_at) %></h2>
            </div>

            <div class="my-2">
                <% if @topic.pinned? %>
                    <%= link_to 'unpin', topic_unpin_path(@topic), class: "btn", data: { 'turbo-method' => :post, 'turbo-confirm': 'unpin for everyone?' } %>
                <% else %>
                    <%= link_to 'pin', topic_pin_path(@topic), class: "btn", data: { 'turbo-method' => :post, 'turbo-confirm': 'pin for everyone?' } %>
                <% end %>

                <% if @topic.starred_for?(current_user) %>
                    <%= link_to 'unstar', topic_unstar_path(@topic), class: "btn btn-cta", data: { 'turbo-method' => :post } %>
                <% else %>
                    <%= link_to 'star', topic_star_path(@topic), class: "btn btn-cta", data: { 'turbo-method' => :post } %>
                <% end %>
            </div>
        </div>

        <% @topic.posts.select{|p| p.persisted? }.each_with_index do |post, index| %>
            <% if index.zero? %>
                <div class="bg-primary-300 px-2 py-3">
                    <div class="px-1 whitespace-pre-line"><%= format_body(post.body) %></div>
                </div>
            <% else %>
                <div class="<%= SiteTheme.pick_color(index) %> py-1 px-2 my-1">
                    <div class="flex justify-between">
                        <div class="text-sm font-medium"><%= link_to post.author.username, profile_path(post.author) %></div>
                        <div class="text-xs text-secondary-900"><%= time_ago_in_words(post.created_at) %></div>
                    </div>
                    <div class="whitespace-pre-line px-1"><%= format_body(post.body) %></div>
                </div>
            <% end %>
        <% end %>
    </div>
</div>

<%= form_with(model: @new_post, url: [@topic], method: :put, class: "py-2", id: "last-post") do |f| %>
    <%= render 'shared/errors', errors: @new_post.errors %>

    <%= f.label :body, "reply", class: "block font-semibold text-primary-100" %>
    <%= f.text_area :body, class: "form-textarea border-none w-full md:w-6/12 h-36 py-1 px-1 mb-3 bg-primary-100" %>

    <%= f.submit "post", class: "block btn" %>
<% end %>

<%= link_to "back to topics", root_path, class: "link--light" %>

app/views/topics/starred.html.erb
<% title("Starred topics") %>

<div class="flex justify-between">
    <h1 class="text-lg mb-1 px-1 inline-block bg-secondary-700 text-white">topics you've starred</h1>
    <%= link_to "new topic", new_topic_path, class: "btn inline-block" %>
</div>

<%= render 'table', topics: @topics, topic_follows: @topic_follows, topic_views: @topic_views, mentions: @mentions %>

<%= link_to "back to topics", topics_path, class: "link mb-3" %>