config/routes.rb
Rails.application.routes.draw do
  if Rails.configuration.x.invitations.enabled
    devise_for :users, controllers: { invitations: 'users/invitations' }
  else
    devise_for :users, skip: :invitations
  end
  get 'directory', to: 'users#index', as: :user_directory
  
  resources :topics, except: %i[edit delete], constraints: { id: /\d+/ } do
    post 'star', to: 'topics#star', as: :star
    post 'unstar', to: 'topics#unstar', as: :unstar
    post 'pin', to: 'topics#pin', as: :pin
    post 'unpin', to: 'topics#unpin', as: :unpin
  end
  get 'topics/mentions', to: 'topics#mentions', as: :my_mentions
  get 'topics/starred', to: 'topics#starred', as: :my_starred
  post 'topics/mark_as_read', to: 'topics#mark_as_read', as: :mark_as_read

  resources :profile, only: %i[show edit update], param: :username
  get 'profile', to: 'profile#mine', as: :my_profile

  root 'topics#index'
end

app/views/shared/_errors.html.erb
<% if errors.any? %>
    <div id="error_explanation" class="bg-primary-200 py-2 px-3 mb-3 w-full md:w-6/12">
        <h2>
        <%= I18n.t("errors.messages.not_saved", count: errors.count)
        %>
        </h2>
        <ul class="list-disc">
            <% errors.full_messages.each do |message| %>
                <li class="ml-5"><%= message.downcase %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_pagination_controls.html.erb
<% link_classes = [] unless local_assigns.has_key?(:link_classes) %>

<% if @page_number > 0 %>
    <%= link_to '< newer', topics_path(page: @page_number - 1), class: "#{link_classes.join(' ')} inline-block" %>
<% end %>
<% if @page_number < @total_pages %>
    <%= link_to 'older >', topics_path(page: @page_number + 1), class: "#{link_classes.join(' ')} inline-block" %>
<% end %>