config/routes.rb
Rails.application.routes.draw do
  if Rails.configuration.x.invitations.enabled
    devise_for :users, controllers: { invitations: 'users/invitations' }
  else
    devise_for :users, skip: :invitations
  end
  get 'directory', to: 'users#index', as: :user_directory
  
  resources :topics, except: %i[edit delete], constraints: { id: /\d+/ } do
    post 'star', to: 'topics#star', as: :star
    post 'unstar', to: 'topics#unstar', as: :unstar
    post 'pin', to: 'topics#pin', as: :pin
    post 'unpin', to: 'topics#unpin', as: :unpin
  end
  get 'topics/mentions', to: 'topics#mentions', as: :my_mentions
  get 'topics/starred', to: 'topics#starred', as: :my_starred
  post 'topics/mark_as_read', to: 'topics#mark_as_read', as: :mark_as_read

  resources :profile, only: %i[show edit update], param: :username
  get 'profile', to: 'profile#mine', as: :my_profile

  root 'topics#index'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :registerable, :timeoutable, and :omniauthable
  devise :invitable, :database_authenticatable,
         :recoverable, :rememberable, :validatable,
         :trackable, :lockable, :invitable

  has_one :profile

  has_many :created_topics, class_name: 'Topic', foreign_key: 'author_id'
  has_many :posts, foreign_key: 'author_id'
  has_many :topic_views, -> { order(created_at: :desc) }
  has_many :topic_follows, -> { order(created_at: :desc) }
  has_many :invitations, class_name: 'User', as: :invited_by

  before_create { build_profile }

  validate :validate_username
  validates_format_of :username, with: /^[a-zA-Z0-9_\.]*$/, :multiline => true
  validates :username, uniqueness: { case_sensitive: false }, presence: true

  scope :accepted_invite, -> { created_by_invite.invitation_accepted }
  scope :created_by_admin, -> { where(invitation_created_at: nil) }
  
  scope :postable, -> { accepted_invite.or(created_by_admin).order('created_at DESC') }

  def has_invites_available?
    return true if invitations.none?
    invitations.order(invitation_created_at: :desc).limit(1).pluck(:invitation_created_at).first < DateTime.now.beginning_of_month
  end

  def validate_username
    if User.where(email: username).exists?
      errors.add(:username, :invalid)
    end
  end

  def to_param
    username
  end

  attr_writer :login

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_h).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    elsif conditions.has_key?(:username) || conditions.has_key?(:email)
      where(conditions.to_h).first
    end
  end
end

app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController
    before_action :configure_permitted_parameters
    before_action :verify_invites_available, only: %i[new]

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:accept_invitation, keys: [:username, :password, :password_confirmation, :invitation_token])
    end

    def verify_invites_available
      raise ActionController::RoutingError.new('Not Found') unless current_user.has_invites_available?
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.includes(:profile).postable
    end
end

app/views/users/invitations/edit.html.erb
<% title("Accept invite") %>

<h1 class="text-lg mb-1 px-1 inline-block bg-secondary-300">accept invite</h1>

<%= form_for(resource, as: resource_name, url: invitation_path(resource_name), html: { method: :put }) do |f| %>
  <%= render "devise/shared/error_messages", resource: resource %>

  <%= f.hidden_field :invitation_token, readonly: true %>

  <div class="field">
  <%= f.label :username, 'username', class: "block font-semibold text-primary-100" %>
  <%= f.text_field :username, autofocus: true, autocomplete: "username", autocapitalize: "off", spellcheck: "false", class: "border-none w-full md:w-6/12 py-1 px-1 mb-3 bg-primary-100" %>
  </div>
  
  <% if f.object.class.require_password_on_accepting %>
    <div class="field">
      <%= f.label :password, "new password", class: "block font-semibold text-primary-100" %>
      <% if @minimum_password_length %>
        <em>(<%= @minimum_password_length %> characters minimum)</em><br />
      <% end %>
      <%= f.password_field :password, autocomplete: "new-password", autocapitalize: "off", spellcheck: "false", class: "border-none w-full md:w-6/12 py-1 px-1 mb-3 bg-primary-100" %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation, "confirm new password", class: "block font-semibold text-primary-100" %>
      <%= f.password_field :password_confirmation, autocomplete: "new-password", autocapitalize: "off", spellcheck: "false", class: "border-none w-full md:w-6/12 py-1 px-1 mb-3 bg-primary-100" %>
    </div>
  <% end %>

  <div class="actions py-3">
    <%= f.submit "create account", class: "btn", data: { turbo: false } %>
  </div>
<% end %>

app/views/users/invitations/new.html.erb
<% title("Invite") %>

<h1 class="text-lg mb-1 px-1 inline-block bg-secondary-300">invite new person</h1>

<%= form_for(resource, as: resource_name, url: invitation_path(resource_name), html: { method: :post }) do |f| %>
  <%= render "devise/shared/error_messages", resource: resource %>

  <div class="field">
    <%= f.label :email, 'email', class: "block font-semibold text-primary-100" %>
    <%= f.email_field :email, autofocus: true, autocomplete: "email", autocapitalize: "off", spellcheck: "false", class: "border-none w-full md:w-6/12 py-1 px-1 mb-3 bg-primary-100" %>
  </div>

  <div class="actions py-3">
    <%= f.submit "invite", class: "btn", data: { turbo: false } %>
  </div>
<% end %>