config/routes.rb
Rails.application.routes.draw do
  if Rails.configuration.x.invitations.enabled
    devise_for :users, controllers: { invitations: 'users/invitations' }
  else
    devise_for :users, skip: :invitations
  end
  get 'directory', to: 'users#index', as: :user_directory
  
  resources :topics, except: %i[edit delete], constraints: { id: /\d+/ } do
    post 'star', to: 'topics#star', as: :star
    post 'unstar', to: 'topics#unstar', as: :unstar
    post 'pin', to: 'topics#pin', as: :pin
    post 'unpin', to: 'topics#unpin', as: :unpin
  end
  get 'topics/mentions', to: 'topics#mentions', as: :my_mentions
  get 'topics/starred', to: 'topics#starred', as: :my_starred
  post 'topics/mark_as_read', to: 'topics#mark_as_read', as: :mark_as_read

  resources :profile, only: %i[show edit update], param: :username
  get 'profile', to: 'profile#mine', as: :my_profile

  root 'topics#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full bg-primary-700">
  <head>
    <title>
      <%= "#{sanitize(yield(:title))} · " if content_for?(:title) %>
      <%= Rails.application.credentials.website_name %>
    </title>
    <%= yield(:cache_control) if content_for?(:cache_control) %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('favicon.png') %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body class="h-full">
    <nav class="w-full bg-primary-200 py-1 px-1 flex justify-between">
      <%= link_to 'home', root_path, class: 'link--dark' %>
      <div>
      <% if user_signed_in? %>
          <%= link_to 'directory', user_directory_path, class: 'px-1 link--dark' %>
          <%= link_to '*s', my_starred_path, class: 'px-1 link--dark' %>
          <%= link_to '@s', my_mentions_path, class: 'px-1 link--dark' %>
          <%= link_to 'my profile', my_profile_path, class: 'px-1 link--dark' %>
          <%= link_to "sign out", destroy_user_session_path, method: :delete, class: "px-1 link--dark", data: { turbo_method: "delete" } %>
        <% else %>
          <%= link_to "sign in", new_user_session_path, class: 'link--dark' %>
        <% end %>
      </div>
    </nav>
    <div class="w-full snow">
      <p class="px-1 bg-secondary-200 text-black"><%= notice %></p>
      <p class="px-1 bg-secondary-100 text-black"><%= alert %></p>
    </div>
    <div class="py-5 px-3">
      <%= yield %>
    </div>
    <div class="text-sm text-white py-1 px-3">
    <p>Cursors by:</p>
    <ul class="list-disc px-3">
      <li class="link"><a target="_blank" href="https://icons8.com/icon/fRieeV3aJTWE/watermelon">Watermelon</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a></li>
      <li class="link"><a target="_blank" href="https://icons8.com/icon/80746/tomato">Tomato</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a></li>
      <li class="link"><a target="_blank" href="https://icons8.com/icon/17570/beach-ball">Beach Ball</a> icon by <a target="_blank" href="https://icons8.com">Icons8</a></li>
    </ul>
    </div>
  </body>
</html>